try:
  x = "Hello Try except Block"
  print(y)
except Exception as e:
    print(f"An unexpected error occured: {e}")
